"""update token table to support more token

Revision ID: 1309c1bf37d7
Revises: f4b8152a4bb2
Create Date: 2023-12-25 17:04:13.511702

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1309c1bf37d7'
down_revision: Union[str, None] = 'f4b8152a4bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('type', sa.String(), nullable=False, comment='令牌类型'))
    op.add_column('token', sa.Column('content', sa.JSON(), nullable=True, comment='令牌内容'))
    op.drop_index('ix_token_id', table_name='token')
    op.create_index(op.f('ix_token_type'), 'token', ['type'], unique=False)
    op.drop_column('token', 'expires_at')
    op.drop_column('token', 'is_expired')
    op.drop_column('token', 'id')
    op.drop_column('token', 'access_token')
    op.drop_column('token', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token',
                  sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True, comment='刷新令牌'))
    op.add_column('token',
                  sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True, comment='访问令牌'))
    op.add_column('token', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='令牌ID'))
    op.add_column('token',
                  sa.Column('is_expired', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否已过期'))
    op.add_column('token',
                  sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=True, comment='过期时间'))
    op.drop_index(op.f('ix_token_type'), table_name='token')
    op.create_index('ix_token_id', 'token', ['id'], unique=False)
    op.drop_column('token', 'content')
    op.drop_column('token', 'type')
    # ### end Alembic commands ###
