"""update goodsinfo table

Revision ID: b6cdbb072979
Revises: 1309c1bf37d7
Create Date: 2024-01-12 00:11:56.546069

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b6cdbb072979'
down_revision: Union[str, None] = '1309c1bf37d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_info', sa.Column('variety', sa.String(length=50), nullable=True, comment='品种'))
    op.add_column('goods_info', sa.Column('color', sa.String(length=50), nullable=True, comment='花色'))
    op.add_column('goods_info', sa.Column('occasion', sa.String(length=50), nullable=True, comment='使用场合'))
    op.alter_column('goods_info', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='商品名称')
    op.alter_column('goods_info', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='数量')
    op.alter_column('goods_info', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='单价')
    op.alter_column('goods_info', 'description',
               existing_type=sa.TEXT(),
               comment='商品描述',
               existing_comment='描述',
               existing_nullable=True)
    op.drop_constraint('goods_info_name_key', 'goods_info', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('goods_info_name_key', 'goods_info', ['name'])
    op.alter_column('goods_info', 'description',
               existing_type=sa.TEXT(),
               comment='描述',
               existing_comment='商品描述',
               existing_nullable=True)
    op.alter_column('goods_info', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='单价')
    op.alter_column('goods_info', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='数量')
    op.alter_column('goods_info', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='商品名称')
    op.drop_column('goods_info', 'occasion')
    op.drop_column('goods_info', 'color')
    op.drop_column('goods_info', 'variety')
    # ### end Alembic commands ###
