"""新增token表，用于outlook，alipay等

Revision ID: da373f787d12
Revises: 980bb28df17d
Create Date: 2023-12-23 23:06:23.518500

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'da373f787d12'
down_revision: Union[str, None] = '980bb28df17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('access_token', sa.String(), nullable=True),
                    sa.Column('refresh_token', sa.String(), nullable=True),
                    sa.Column('expires_at', sa.Integer(), nullable=True),
                    sa.Column('is_expired', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
